Active=Active
Automation=Automation
Boolean=Boolean
Cancelled=Cancelled
Closed=Closed
Completed=Completed
Critical=Critical
Custom\ String=Custom String
Date=Date
Date\ and\ Time=Date and Time
Development=Development
Future=Future
High=High
In\ Progress=In Progress
Low=Low
Medium=Medium
Manpower\ Supply=Manpower Supply
Numeric\ (decimals)=Numeric (decimals)
Numeric\ (without\ decimals)=Numeric (without decimals)
On\ Hold=On Hold
Others=Others
Past=Past
Program\ Management=Program Management
Ready\ To\ Start=Ready To Start
SOW\ Type=SOW Type
String=String
Testing=Testing
Work\ Item\ Priority=Work Item Priority